/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
static yyconst short int yy_accept[384] =
    {   0,
        0,    0,  109,  107,  106,  106,   94,  107,  100,   93,
      107,   88,   89,   98,   97,   85,   96,   92,   99,   51,
       50,   86,   82,  101,   87,  102,  105,   48,   48,   90,
       91,  103,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   83,  104,
       84,   95,   81,    0,   59,    0,   67,   84,   76,   68,
        0,    0,   65,   73,   63,   74,   64,   75,    0,   54,
        1,    2,   66,   55,   51,    0,    0,   51,   51,    0,
       51,   50,   50,   50,   50,   91,   83,   90,   72,   78,
       80,   79,   71,   48,    0,    0,   69,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   10,   48,   48,   48,   48,   48,   48,   18,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   70,   77,   59,    0,    0,    0,    0,   52,
        0,    0,   60,    0,   54,    2,    0,   55,    0,   53,
       51,   51,   51,   51,    0,   49,   50,   50,   50,   50,
       62,   61,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   16,   48,   48,   20,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,    0,    0,    0,    0,    0,   54,    0,
       55,   53,   51,    0,    0,   49,    0,   49,   49,   50,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
        3,   48,    5,    6,   48,   48,   48,   48,   12,   13,
       48,   48,   17,   48,   21,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   34,   48,   48,
        0,    0,    0,    0,    0,    0,   49,   49,    0,   56,
       49,   49,   48,   48,   40,   48,   48,   48,   48,   48,
       48,   48,    4,    7,   48,   48,   48,   48,   15,   48,
       48,   48,   48,   25,   48,   48,   48,   48,   48,   48,

       32,   48,   48,   36,    0,   57,    0,   58,   56,   49,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   11,   14,   19,   48,   48,   24,   26,   27,   28,
       29,   30,   48,   48,   48,   57,   58,   48,   48,   39,
       48,   48,   48,   48,   48,   48,   48,   48,    9,   48,
       48,   31,   48,   48,   37,   38,   41,   42,   48,   48,
       48,   48,   47,    8,   22,   23,   33,   35,   48,   44,
       48,   48,   43,   48,   48,   48,   48,   48,   48,   48,
       46,   45,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   34,   34,   36,   34,   37,   34,   38,
       34,   34,   39,   40,   41,   34,   34,   42,   34,   34,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   34,   57,   58,   59,   60,
       61,   62,   34,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[76] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    7,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    7,
        7,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    3,    1,    1,    8,    6,    6,    7,
        7,    7,    6,    8,    8,    8,    8,    8,    8,    9,
        8,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[394] =
    {   0,
        0,    0,  692,  693,  693,  693,  667,   71,   53,   72,
      646,  693,  693,  665,   68,  693,   69,   67,   79,  101,
       92,  663,  693,  124,  663,   64,  693,    0,   92,  693,
      693,  662,  136,  619,  621,   43,   47,   66,   44,  622,
       53,  621,  629,   84,  610,  117,  618,  623,  693,   93,
      693,  693,  693,  124,  152,  143,  693,  693,  693,  693,
      130,  161,  693,  693,  693,  693,  693,  693,  662,  167,
      693,    0,  693,  190,  214,  221,  177,  115,  144,  661,
      196,  250,  187,  146,  205,  693,  693,  693,  651,  693,
      693,  693,  650,    0,  157,  629,  693,   69,  611,  610,

      618,  610,  607,  602,  611,  612,  599,  611,  598,  613,
      600,  606,  592,  593,  590,  590,  593,  590,  587,    0,
      148,  591,  151,  589,   60,  196,  593,  586,  642,  136,
      191,  590,  693,  693,  273,  640,  255,  277,    0,  693,
      271,    0,  693,  286,  693,    0,  305,  693,  293,  309,
      217,  693,  608,  585,    0,  315,  252,  693,  606,  583,
      693,  693,  584,  578,  577,  578,  576,  587,  571,  585,
      569,  565,  569,  581,  576,  564,  192,  578,  576,  572,
      564,  570,  573,    0,  559,  563,    0,  564,  561,  551,
      549,  535,  535,  542,  527,  522,  522,  533,  512,  515,

      511,  511,  500,  315,  377,  326,  423,  318,  366,  329,
      427,  693,  693,  152,  173,  314,  346,  241,  313,  693,
      503,  497,  496,  491,  500,  497,  498,  484,  496,  487,
        0,  489,    0,    0,  480,  488,  477,  484,    0,    0,
      478,  475,    0,  479,    0,  472,  472,  470,  465,  477,
      467,  471,  475,  474,  472,  458,  463,    0,  451,  462,
      246,    0,  253,    0,  398,  469,  327,  693,  370,  473,
      477,  454,  450,  452,    0,  449,  443,  448,  438,  446,
      453,  450,    0,    0,  435,  436,  432,  422,    0,  427,
      413,  421,  410,    0,  418,  415,  416,  400,  409,  410,

        0,  401,  404,    0,  415,  479,  419,  502,  693,  693,
      313,  408,  405,  400,  389,  382,  373,  371,  373,  348,
      348,    0,    0,    0,  359,  353,    0,    0,    0,    0,
        0,    0,  348,  348,  341,  693,  693,  328,  338,    0,
      309,  326,  327,  309,  322,  310,  305,  290,    0,  277,
      266,    0,  256,  249,    0,    0,    0,    0,  233,  232,
      239,  227,    0,    0,    0,    0,    0,    0,  214,    0,
      200,  166,    0,  160,  167,  120,   98,   78,   43,   16,
        0,    0,  693,  560,  569,  573,  580,  587,  596,  601,
      603,  605,  607

    } ;

static yyconst short int yy_def[394] =
    {   0,
      383,    1,  383,  383,  383,  383,  383,  384,  383,  383,
      385,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  386,  386,  383,
      383,  383,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  383,  383,
      383,  383,  383,  384,  383,  387,  383,  383,  383,  383,
      385,  388,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  389,  383,  383,  383,  383,  383,  383,  383,  390,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  386,  384,  385,  383,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  383,  383,  383,  383,  383,  384,  391,  383,
      385,  392,  383,  383,  383,  389,  383,  383,  383,  383,
      383,  383,  383,  383,  393,  390,  383,  383,  383,  383,
      383,  383,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  384,  384,  385,  385,  383,  383,  383,
      383,  383,  383,  393,  393,  383,  383,  383,  383,  383,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      384,  205,  385,  207,  383,  383,  383,  383,  383,  383,
      383,  383,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  383,  383,  383,  383,  383,  383,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  383,  383,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,    0,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383

    } ;

static yyconst short int yy_nxt[769] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       29,   28,   30,    4,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   28,   41,   28,   42,   28,   28,
       28,   28,   43,   44,   45,   46,   47,   48,   28,   28,
       28,   49,   50,   51,   52,   55,   57,   58,   59,   64,
      382,   69,   66,   70,   70,   70,   70,   92,   93,   71,
      109,   65,   67,   68,   72,   60,   95,  110,  112,   96,

      381,  117,   73,  111,  118,  120,   74,  113,   82,   82,
       82,   82,  121,  193,   56,   74,  133,   75,   75,   76,
       76,   95,   77,  114,   96,  115,  163,   83,   55,   87,
      194,   77,   84,  164,  116,  129,   78,  140,  124,  125,
      380,   79,   80,   77,   88,  379,   89,   90,  126,   85,
      151,  127,   77,  135,  135,  152,   95,   84,   81,  138,
      138,   55,   98,   99,  100,  134,   79,   56,  101,   80,
      102,  378,  103,   62,  104,  105,  130,  141,  141,  153,
      152,  159,  106,   70,   70,   70,   70,  136,  149,  265,
      149,  199,  136,  150,  150,  150,  150,  144,  145,  200,

       56,  154,  145,  160,  189,  186,   70,   70,   70,   70,
      266,  139,  187,  265,  190,  191,  377,  137,  144,  145,
      147,  148,  157,  376,  145,  148,  375,  158,   74,  142,
       75,   75,   76,   76,  266,   74,  152,   76,   76,   76,
       76,  147,  148,  195,   77,  158,  201,  148,  202,   78,
       55,   77,  158,  151,   79,  235,  236,  152,  196,   95,
      140,  152,  157,  374,   74,   77,   82,   82,   82,   82,
      158,   81,   77,  136,  135,  135,  271,   95,  140,   79,
       77,   55,  152,  373,  372,   83,  371,  206,  206,   56,
       84,  370,  158,  204,  204,  369,   62,  208,  272,  208,

      368,   77,  209,  209,  209,  209,  367,   85,  136,  150,
      150,  150,  150,  136,   62,   84,  210,  158,  210,   55,
       56,  211,  211,  211,  211,  150,  150,  150,  150,  215,
      366,  261,  261,  140,  209,  209,  209,  209,  137,  365,
      212,  364,  263,  263,  212,  211,  211,  211,  211,  267,
      216,  363,  217,  268,  268,  218,  362,  269,   56,  269,
      338,  212,  270,  270,  270,  270,  212,  268,  361,   62,
      267,  360,  219,  339,  359,  358,  217,  357,  268,  268,
      218,   55,  209,  209,  209,  209,  270,  270,  270,  270,
      356,  355,  268,  262,  262,  262,  262,  145,  354,  353,

      352,  145,  351,  262,  262,  262,  262,  262,  262,  305,
      350,  305,  349,  348,  306,  306,  306,  306,  145,  347,
       56,  346,  345,  145,  262,  262,  262,  262,  262,  262,
      140,  306,  306,  306,  306,  308,  308,  308,  308,  264,
      264,  264,  264,  211,  211,  211,  211,  344,  343,  264,
      264,  264,  264,  264,  264,  342,  341,  340,  148,  335,
      334,  333,  148,  332,  331,  330,   62,  329,  328,  327,
      264,  264,  264,  264,  264,  264,  326,  325,  324,  148,
      307,  323,  307,  322,  148,  308,  308,  308,  308,  270,
      270,  270,  270,  321,  320,  306,  306,  306,  306,  319,

      318,  317,  316,  315,  309,  314,  313,  312,  309,  311,
      336,  310,  310,  304,  336,  303,  302,  301,  308,  308,
      308,  308,  300,  299,  298,  309,  297,  296,  295,  294,
      309,  336,  293,  337,  292,  291,  336,  337,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  337,  274,  273,  260,  259,  337,
       54,  258,   54,   54,   54,   54,   54,   54,   54,   61,
      257,   61,  256,   61,   61,   61,   61,   61,   94,   94,
       94,   94,   54,   54,  255,   54,  254,  253,   54,   61,
       61,  252,   61,  251,  250,   61,  146,  249,  146,  146,

      146,  146,  146,  146,  146,  156,  156,  156,  205,  205,
      207,  207,  214,  214,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  220,  213,  213,   95,  203,   95,  198,  197,  192,
      188,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,   62,  162,  161,  155,  143,  132,  131,  128,
      123,  122,  119,  108,  107,   97,   91,   86,   63,   62,
       53,  383,    3,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383
    } ;

static yyconst short int yy_chk[769] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,    9,   10,   15,
      380,   18,   17,   18,   18,   18,   18,   26,   26,   19,
       36,   15,   17,   17,   19,   10,   29,   36,   37,   29,

      379,   39,   19,   36,   39,   41,   21,   37,   21,   21,
       21,   21,   41,  125,    8,   20,   50,   20,   20,   20,
       20,   46,   21,   38,   46,   38,   98,   21,   54,   24,
      125,   20,   21,   98,   38,   46,   20,   61,   44,   44,
      378,   20,   20,   21,   24,  377,   24,   24,   44,   21,
       78,   44,   20,   55,   55,   78,   55,   21,   20,   56,
       56,   95,   33,   33,   33,   50,   20,   54,   33,   20,
       33,  376,   33,   61,   33,   33,   46,   62,   62,   79,
       78,   84,   33,   70,   70,   70,   70,   55,   77,  214,
       77,  130,   55,   77,   77,   77,   77,   70,   70,  130,

       95,   79,   70,   84,  123,  121,   74,   74,   74,   74,
      215,   56,  121,  214,  123,  123,  375,   55,   70,   70,
       74,   74,   83,  374,   70,   74,  372,   83,   75,   62,
       75,   75,   75,   75,  215,   76,   81,   76,   76,   76,
       76,   74,   74,  126,   75,   85,  131,   74,  131,   75,
      261,   76,   83,   81,   75,  177,  177,  151,  126,  137,
      263,   81,   85,  371,   82,   75,   82,   82,   82,   82,
       85,   75,   76,  137,  135,  135,  218,  135,  141,   75,
       82,  138,  151,  369,  362,   82,  361,  141,  141,  261,
       82,  360,  157,  138,  138,  359,  263,  144,  218,  144,

      354,   82,  144,  144,  144,  144,  353,   82,  135,  149,
      149,  149,  149,  135,  141,   82,  147,  157,  147,  204,
      138,  147,  147,  147,  147,  150,  150,  150,  150,  156,
      351,  204,  204,  206,  208,  208,  208,  208,  135,  350,
      150,  348,  206,  206,  150,  210,  210,  210,  210,  216,
      156,  347,  156,  219,  216,  156,  346,  217,  204,  217,
      311,  150,  217,  217,  217,  217,  150,  267,  345,  206,
      219,  344,  156,  311,  343,  342,  156,  341,  219,  216,
      156,  205,  209,  209,  209,  209,  269,  269,  269,  269,
      339,  338,  267,  205,  205,  205,  205,  209,  335,  334,

      333,  209,  326,  205,  205,  205,  205,  205,  205,  265,
      325,  265,  321,  320,  265,  265,  265,  265,  209,  319,
      205,  318,  317,  209,  205,  205,  205,  205,  205,  205,
      207,  305,  305,  305,  305,  307,  307,  307,  307,  207,
      207,  207,  207,  211,  211,  211,  211,  316,  315,  207,
      207,  207,  207,  207,  207,  314,  313,  312,  211,  303,
      302,  300,  211,  299,  298,  297,  207,  296,  295,  293,
      207,  207,  207,  207,  207,  207,  292,  291,  290,  211,
      266,  288,  266,  287,  211,  266,  266,  266,  266,  270,
      270,  270,  270,  286,  285,  306,  306,  306,  306,  282,

      281,  280,  279,  278,  270,  277,  276,  274,  270,  273,
      306,  272,  271,  260,  306,  259,  257,  256,  308,  308,
      308,  308,  255,  254,  253,  270,  252,  251,  250,  249,
      270,  306,  248,  308,  247,  246,  306,  308,  244,  242,
      241,  238,  237,  236,  235,  232,  230,  229,  228,  227,
      226,  225,  224,  223,  308,  222,  221,  203,  202,  308,
      384,  201,  384,  384,  384,  384,  384,  384,  384,  385,
      200,  385,  199,  385,  385,  385,  385,  385,  386,  386,
      386,  386,  387,  387,  198,  387,  197,  196,  387,  388,
      388,  195,  388,  194,  193,  388,  389,  192,  389,  389,

      389,  389,  389,  389,  389,  390,  390,  390,  391,  391,
      392,  392,  393,  393,  191,  190,  189,  188,  186,  185,
      183,  182,  181,  180,  179,  178,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      160,  159,  154,  153,  136,  132,  129,  128,  127,  124,
      122,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   96,   93,   89,   80,   69,   48,   47,   45,
       43,   42,   40,   35,   34,   32,   25,   22,   14,   11,
        7,    3,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c_compiler.l"
#define INITIAL 0
#line 25 "c_compiler.l"
#include <stdio.h>
#include "c_compiler.tab.h"

extern void yyerror(const char *);  /* prints grammar violation message */

extern int sym_type(const char *);  /* TOKs type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

static void comment(void);
static int check_type(void);


#include<strings.h>
extern SYMTABNODEPTR symTab[SYMTABSIZE];
extern int currentSymTabSize;

#define TOK(t) return(t);
#define TOK_I(t) {yylval.iVal = atoi(yytext);return(t);}
#define TOK_F(t) {yylval.fVal = atof(yytext);return(t);}
#define TOK_S(t) {yylval.sVal = strdup(yytext);return(t);}
#define TOK_ID(t) {yylval.sVal = strdup(yytext);return (t);}
#line 686 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 49 "c_compiler.l"

#line 839 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 384 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 693 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "c_compiler.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "c_compiler.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "c_compiler.l"
{ TOK(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "c_compiler.l"
{ TOK(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "c_compiler.l"
{ TOK(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "c_compiler.l"
{ TOK(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "c_compiler.l"
{ TOK(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "c_compiler.l"
{ TOK(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "c_compiler.l"
{ TOK(DEFAULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "c_compiler.l"
{ TOK(DO); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "c_compiler.l"
{ TOK(DOUBLE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "c_compiler.l"
{ TOK(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "c_compiler.l"
{ TOK(ENUM); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "c_compiler.l"
{ TOK(EXTERN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "c_compiler.l"
{ TOK(FLOAT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "c_compiler.l"
{ TOK(FOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "c_compiler.l"
{ TOK(GOTO); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "c_compiler.l"
{ TOK(IF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "c_compiler.l"
{ TOK(INLINE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "c_compiler.l"
{ TOK(INT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "c_compiler.l"
{ TOK(LONG); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "c_compiler.l"
{ TOK(REGISTER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "c_compiler.l"
{ TOK(RESTRICT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "c_compiler.l"
{ TOK(RETURN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "c_compiler.l"
{ TOK(SHORT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "c_compiler.l"
{ TOK(SIGNED); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "c_compiler.l"
{ TOK(SIZEOF); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "c_compiler.l"
{ TOK(STATIC); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "c_compiler.l"
{ TOK(STRUCT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "c_compiler.l"
{ TOK(SWITCH); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "c_compiler.l"
{ TOK(TYPEDEF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "c_compiler.l"
{ TOK(UNION); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "c_compiler.l"
{ TOK(UNSIGNED); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "c_compiler.l"
{ TOK(VOID); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "c_compiler.l"
{ TOK(VOLATILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "c_compiler.l"
{ TOK(WHILE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "c_compiler.l"
{ TOK(ALIGNAS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "c_compiler.l"
{ TOK(ALIGNOF); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "c_compiler.l"
{ TOK(ATOMIC); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "c_compiler.l"
{ TOK(BOOL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "c_compiler.l"
{ TOK(COMPLEX); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "c_compiler.l"
{ TOK(GENERIC); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "c_compiler.l"
{ TOK(IMAGINARY); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "c_compiler.l"
{ TOK(NORETURN); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "c_compiler.l"
{ TOK(STATIC_ASSERT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "c_compiler.l"
{ TOK(THREAD_LOCAL); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "c_compiler.l"
{ TOK(FUNC_NAME); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "c_compiler.l"
{ TOK(check_type()); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "c_compiler.l"
{ TOK_I(I_CONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "c_compiler.l"
{ TOK_I(I_CONSTANT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "c_compiler.l"
{ TOK_I(I_CONSTANT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "c_compiler.l"
{ TOK_I(I_CONSTANT); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "c_compiler.l"
{ TOK_F(F_CONSTANT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "c_compiler.l"
{ TOK_F(F_CONSTANT); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "c_compiler.l"
{ TOK_F(F_CONSTANT); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "c_compiler.l"
{ TOK_F(F_CONSTANT); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "c_compiler.l"
{ TOK_F(F_CONSTANT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "c_compiler.l"
{ TOK_F(F_CONSTANT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "c_compiler.l"
{ TOK_S(STRING_LITERAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 115 "c_compiler.l"
{ TOK(ELLIPSIS); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 116 "c_compiler.l"
{ TOK(RIGHT_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 117 "c_compiler.l"
{ TOK(LEFT_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 118 "c_compiler.l"
{ TOK(ADD_ASSIGN); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 119 "c_compiler.l"
{ TOK(SUB_ASSIGN); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 120 "c_compiler.l"
{ TOK(MUL_ASSIGN); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 121 "c_compiler.l"
{ TOK(DIV_ASSIGN); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 122 "c_compiler.l"
{ TOK(MOD_ASSIGN); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 123 "c_compiler.l"
{ TOK(AND_ASSIGN); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 124 "c_compiler.l"
{ TOK(XOR_ASSIGN); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 125 "c_compiler.l"
{ TOK(OR_ASSIGN); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 126 "c_compiler.l"
{ TOK(RIGHT_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 127 "c_compiler.l"
{ TOK(LEFT_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 128 "c_compiler.l"
{ TOK(INC_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 129 "c_compiler.l"
{ TOK(DEC_OP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 130 "c_compiler.l"
{ TOK(PTR_OP); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 131 "c_compiler.l"
{ TOK(AND_OP); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 132 "c_compiler.l"
{ TOK(OR_OP); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 133 "c_compiler.l"
{ TOK(LE_OP); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 134 "c_compiler.l"
{ TOK(GE_OP); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 135 "c_compiler.l"
{ TOK(EQ_OP); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 136 "c_compiler.l"
{ TOK(NE_OP); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 137 "c_compiler.l"
{ TOK(';'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 138 "c_compiler.l"
{ TOK('{'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 139 "c_compiler.l"
{ TOK('}'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 140 "c_compiler.l"
{ TOK(','); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 141 "c_compiler.l"
{ TOK(':'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 142 "c_compiler.l"
{ TOK('='); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 143 "c_compiler.l"
{ TOK('('); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 144 "c_compiler.l"
{ TOK(')'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 145 "c_compiler.l"
{ TOK('['); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 146 "c_compiler.l"
{ TOK(']'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 147 "c_compiler.l"
{ TOK('.'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 148 "c_compiler.l"
{ TOK('&'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 149 "c_compiler.l"
{ TOK('!'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 150 "c_compiler.l"
{ TOK('~'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 151 "c_compiler.l"
{ TOK('-'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 152 "c_compiler.l"
{ TOK('+'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 153 "c_compiler.l"
{ TOK('*'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 154 "c_compiler.l"
{ TOK('/'); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 155 "c_compiler.l"
{ TOK('%'); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 156 "c_compiler.l"
{ TOK('<'); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 157 "c_compiler.l"
{ TOK('>'); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 158 "c_compiler.l"
{ TOK('^'); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 159 "c_compiler.l"
{ TOK('|'); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 160 "c_compiler.l"
{ TOK('?'); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 162 "c_compiler.l"
{ /* whitespace separates TOKs */ }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 163 "c_compiler.l"
{ /* discard bad characters */ }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 165 "c_compiler.l"
ECHO;
	YY_BREAK
#line 1462 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 384 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 384 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 383);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 165 "c_compiler.l"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        TOK_ID(IDENTIFIER);
    }
}
